### ISSUE TITLE
Can't open gladdy / won't let me see the frames

### ISSUE THREAD

**Issue by ghost** [Schaka/SchakaPvPUI#3]
Bug grabber: 
2017/06/23 22:25:42-74-x1]: Gladdy\Frame.lua:155: attempt to index field 'frame' (a nil value)
Gladdy\Options.lua:57: in function <Interface\AddOns\Gladdy\Options.lua:54>
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[2]":9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?:
AceConfigDialog-3.0\AceConfigDialog-3.0.lua:781: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:600>
(tail call): ?:
<in C code>: ?
<string>:"safecall Dispatcher[3]":9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?:
AceGUI-3.0\AceGUI-3.0.lua:264: in function `Fire'
...UF\libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:51: in function <...UF\libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:47>:

**Comment by Schaka** [comment]
You are using another addon that brings a conflicting version of Ace3.
Disable your addons, make your settings in Gladdy and enable them again.
