### ISSUE TITLE
Side Bars Griffins

### ISSUE THREAD

**Issue by clarityx56** [Schaka/SchakaPvPUI#4]
The addon by default turns off the side griffins, tell me how i can get them back, in which configuration file it is configured?

[http://www.mediafire.com/convkey/2658/47960cd4k4u2dq7zg.jpg](url)

I tried to find: /run MainMenuBarLeftEndCap:Hide();MainMenuBarRightEndCa p:Hide()

**Comment by Schaka** [comment]
Somewhere in SchakaPvPUI there's something about MainMenuBar, but I believe it's actually not called RightEndCap. Gotta look in the main file, which hides the gryphons.
